DROP TABLE DIRECT_DEBITS;

CREATE TABLE DIRECT_DEBITS
(
    ACCOUNT_NAME VARCHAR2(30) NOT NULL,
    BALANCE VARCHAR2(30),
    STATEMENT_DATE DATE,
    BUFFER_DAYS NUMERIC,
    DD_DATE DATE,
    BANK VARCHAR2(10) NOT NULL,
    CREDIT_LIMIT NUMERIC(10),
    CREDIT_PERCENT DECIMAL(6),
    PRIMARY KEY (ACCOUNT_NAME)
);

INSERT INTO DIRECT_DEBITS VALUES('THREE', 8, TO_DATE('18/11/2024', 'DD/MM/YYYY'), 7, TO_DATE('25/11/2024', 'DD/MM/YYYY'), 'NATWEST', 0, 0);